In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import scipy.io
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
Mat1 = scipy.io.loadmat('S1_E1_A1')
Mat2 = scipy.io.loadmat('S1_E1_A2')
Mat3 = scipy.io.loadmat('S1_E1_A3')

In [3]:
data_1 = Mat1['emg']
data_2 = Mat2['emg']
data_3 = Mat3['emg']
target_1 = Mat1['glove']
target_2 = Mat2['glove']
target_3 = Mat3['glove']

In [4]:
df1 = pd.DataFrame(data_1)
df2 = pd.DataFrame(data_2)
df3 = pd.DataFrame(data_3)
tg1 = pd.DataFrame(target_1)
tg2 = pd.DataFrame(target_2)
tg3 = pd.DataFrame(target_3)

In [5]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003

In [6]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-6.892924e-07,-0.000007,-4.160127e-06,2.543357e-06,-0.000004,2.467728e-08,-0.000004,5.223993e-08,4.872679e-06,0.000005,5.961380e-07,0.000005,1.334032e-06,-0.000002,2.133135e-07,-5.790907e-07
1,-1.911244e-06,-0.000007,-4.672071e-06,-6.955908e-08,-0.000005,1.083521e-06,-0.000003,4.331919e-07,1.800991e-06,0.000006,1.637810e-06,0.000004,3.867504e-07,-0.000003,6.066755e-07,-1.272035e-06
2,-2.690005e-06,-0.000007,-3.330392e-06,-1.262497e-06,-0.000006,3.104114e-06,-0.000002,1.058151e-06,-7.933618e-07,0.000002,4.638380e-07,0.000001,-1.800234e-07,-0.000005,2.813287e-07,-1.034752e-06
3,-2.914218e-06,-0.000006,-7.130482e-07,-7.396711e-07,-0.000010,6.994653e-06,-0.000001,9.734867e-07,-3.303827e-06,-0.000005,-1.321765e-06,-0.000001,2.873094e-07,-0.000009,-3.542030e-07,2.917104e-07
4,-2.950499e-06,-0.000004,1.092567e-07,-5.845535e-07,-0.000009,5.697710e-06,-0.000003,1.089384e-06,6.329613e-08,-0.000004,6.139790e-07,-0.000005,-1.138085e-07,-0.000008,1.742499e-07,9.767029e-07

In [7]:
df3.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-0.000037,-0.000082,-0.000004,0.000001,2.204304e-07,6.710034e-07,-0.000005,-0.000007,-0.000006,-2.649602e-06,9.538348e-07,-8.910476e-07,1.757242e-07,1.639383e-06,-0.000004,-4.450985e-07
1,-0.000037,-0.000121,-0.000006,-0.000002,-4.719077e-08,-1.090803e-06,-0.000006,-0.000009,0.000007,-2.917018e-07,-3.453820e-07,-1.362039e-06,-1.890815e-06,1.626923e-06,-0.000004,-9.655273e-07
2,-0.000032,-0.000145,-0.000007,-0.000004,-1.666448e-06,-2.220409e-06,-0.000007,-0.000011,0.000026,-7.816593e-07,-8.085756e-07,1.442957e-06,-2.675261e-06,2.083744e-06,-0.000004,1.104961e-06
3,-0.000027,-0.000157,-0.000009,-0.000006,-9.860713e-07,-4.857274e-06,-0.000009,-0.000011,0.000043,-2.264009e-06,-1.557758e-06,3.817523e-06,-3.826853e-06,1.394467e-06,-0.000004,2.885679e-06
4,-0.000021,-0.000132,-0.000011,-0.000008,-1.351671e-06,-9.463336e-06,-0.000012,-0.000010,0.000046,-2.773675e-06,2.554029e-07,4.450674e-06,-4.164564e-06,7.318045e-07,-0.000006,5.687984e-06

In [8]:
EMG = pd.concat([df1,df2,df3], axis=0)
EMG.shape

(5135095, 16)

In [9]:
EMG.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003

In [10]:
EMG.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5135095 entries, 0 to 529098
Data columns (total 16 columns):
 #   Column  Dtype
---  ------  -----
 0   0       float32
 1   1       float32
 2   2       float32
 3   3       float32
 4   4       float32
 5   5       float32
 6   6       float32
 7   7       float32
 8   8       float32
 9   9       float32
 10  10      float32
 11  11      float32
 12  12      float32
 13  13      float32
 14  14      float32
 15  15      float32
dtypes: float32(16)
memory usage: 352.6 MB

In [11]:
EMG.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
count,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06
mean,8.466411e-09,-1.842094e-07,-3.098294e-10,-9.447673e-11,-1.151123e-09,-7.352579e-10,-7.391698e-10,8.381000e-10,-4.633473e-09,-1.169176e-09,-1.144170e-09,-3.254574e-08,2.882238e-09,-6.486212e-10,3.105959e-08,-6.575405e-10
std,3.138109e-05,4.693620e-05,4.902075e-06,4.262650e-06,1.234445e-05,3.883291e-05,1.252545e-05,1.404126e-05,5.073429e-05,1.266151e-05,4.990268e-06,6.878563e-06,3.853327e-05,2.598077e-05,1.131652e-05,1.464521e-05
min,-9.152096e-04,-1.942183e-03,-1.034595e-04,-1.105371e-04,-6.541168e-04,-1.483897e-03,-3.825000e-04,-5.824306e-04,-1.069842e-03,-3.998122e-04,-4.717583e-05,-2.395028e-04,-1.448422e-03,-7.321497e-04,-4.896206e-04,-5.471918e-04
25%,-7.510078e-06,-9.420879e-06,-2.574322e-06,-2.526801e-06,-3.251968e-06,-5.218468e-06,-4.014682e-06,-3.202528e-06,-1.634931e-05,-5.657384e-06,-3.067547e-06,-3.441960e-06,-5.133208e-06,-5.534016e-06,-2.613644e-06,-3.334542e-06
50%,1.151889e-06,2.232721e-06,9.899731e-08,1.512165e-08,2.675181e-07,1.913958e-07,0.000000e+00,2.091450e-07,2.152981e-06,4.667680e-09,-4.117406e-08,-1.138556e-07,-3.423430e-07,6.472018e-07,1.134401e-07,2.199274e-07
75%,9.020946e-06,1.495654e-05,2.747421e-06,2.573463e-06,3.954990e-06,6.231710e-06,4.157251e-06,3.533766e-06,2.017061e-05,5.822982e-06,3.022782e-06,3.289759e-06,3.715752e-06,7.813156e-06,2.905086e-06,3.718127e-06
max,5.866060e-04,1.272647e-03,1.171567e-04,2.089401e-04,5.052245e-04,1.107698e-03,2.704328e-04,4.218504e-04,6.151334e-04,4.196055e-04,6.285966e-05,2.190010e-04,1.858117e-03,6.020703e-04,4.632727e-04,6.572311e-04

In [12]:
EMG.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [13]:
tg1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,46.5872,-14.424356,22.320053,38.31403,15.359853,33.585068,17.619312,21.458416,11.180698,15.289665,20.117695,5.432144,3.176478,22.531336,8.019753,41.629326,2.820585,5.138314
1,46.5872,-14.424356,22.320053,38.31403,15.359853,33.585068,17.619312,21.458416,11.180698,15.289665,20.117695,5.432144,3.176478,22.531336,8.019753,41.629326,2.820585,5.138314
2,46.5872,-14.424356,22.320053,38.31403,15.359853,33.585068,17.619312,21.458416,11.180698,15.289665,20.117695,5.432144,3.176478,22.531336,8.019753,41.629326,2.820585,5.138314
3,46.5872,-14.424356,22.320053,38.31403,15.359853,33.585068,17.619312,21.458416,11.180698,15.289665,20.117695,5.432144,3.176478,22.531336,8.019753,41.629326,2.820585,5.138314
4,46.5872,-14.424356,22.320053,38.31403,15.359853,33.585068,17.619312,21.458416,11.180698,15.289665,20.117695,5.432144,3.176478,22.531336,8.019753,41.629326,2.820585,5.138314

In [14]:
tg2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,40.064991,-28.202845,22.320053,39.612812,12.47988,31.0016,13.10154,15.020891,10.164271,8.851912,25.411823,2.49585,3.176478,28.968861,5.450496,33.045959,-1.245123,4.009014
1,40.064991,-28.202845,22.320053,39.612812,12.47988,31.0016,13.10154,15.020891,10.164271,8.851912,25.411823,2.49585,3.176478,28.968861,5.450496,33.045959,-1.245123,4.009014
2,40.064991,-28.202845,22.320053,39.612812,12.47988,31.0016,13.10154,15.020891,10.164271,8.851912,25.411823,2.49585,3.176478,28.968861,5.450496,33.045959,-1.245123,4.009014
3,40.064991,-28.202845,22.320053,39.612812,12.47988,31.0016,13.10154,15.020891,10.164271,8.851912,25.411823,2.49585,3.176478,28.968861,5.450496,33.045959,-1.245123,4.009014
4,40.064991,-28.202845,22.320053,39.612812,12.47988,31.0016,13.10154,15.020891,10.164271,8.851912,25.411823,2.49585,3.176478,28.968861,5.450496,33.045959,-1.245123,4.009014

In [15]:
tg3.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,53.109406,-31.647467,22.320053,39.612812,18.239824,35.307377,18.974644,18.239653,10.672484,9.656631,26.47065,5.065107,-1.270591,25.750099,6.551606,34.118881,1.804158,4.912454
1,53.109406,-31.647467,22.320053,39.612812,18.239824,35.307377,18.974644,18.239653,10.672484,9.656631,26.47065,5.065107,-1.270591,25.750099,6.551606,34.118881,1.804158,4.912454
2,53.109406,-31.647467,22.320053,39.612812,18.239824,35.307377,18.974644,18.239653,10.672484,9.656631,26.47065,5.065107,-1.270591,25.750099,6.551606,34.118881,1.804158,4.912454
3,53.109406,-31.647467,22.320053,39.612812,18.239824,35.307377,18.974644,18.239653,10.672484,9.656631,26.47065,5.065107,-1.270591,25.750099,6.551606,34.118881,1.804158,4.912454
4,53.109406,-31.647467,22.320053,39.612812,18.239824,35.307377,18.974644,18.239653,10.672484,9.656631,26.47065,5.065107,-1.270591,25.750099,6.551606,34.118881,1.804158,4.912454

In [16]:
Glove = pd.concat([tg1,tg2,tg3], axis=0)
Glove.shape

(5135095, 18)

In [17]:
Glove = Glove.iloc[:, [4,5]]
Glove.shape

(5135095, 2)

In [18]:
EMG_Target = pd.concat([EMG,Glove], axis=1)
EMG_Target.shape

(5135095, 18)

In [19]:
EMG_Target.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,4,5
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

In [20]:
EMG_Target.columns = ['EMG1','EMG2','EMG3','EMG4','EMG5','EMG6','EMG7',
                      'EMG8','EMG9','EMG10','EMG11','EMG12','EMG13',
                      'EMG14','EMG15','EMG16','indexExtension','indexFlexion']
EMG_Target.head()

,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,EMG7,EMG8,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

In [21]:
EMG_Target.describe()

,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,EMG7,EMG8,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
count,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06,5.135095e+06
mean,8.466411e-09,-1.842094e-07,-3.098294e-10,-9.447673e-11,-1.151123e-09,-7.352579e-10,-7.391698e-10,8.381000e-10,-4.633473e-09,-1.169176e-09,-1.144170e-09,-3.254574e-08,2.882238e-09,-6.486212e-10,3.105959e-08,-6.575405e-10,2.206481e+01,3.360434e+01
std,3.138109e-05,4.693620e-05,4.902075e-06,4.262650e-06,1.234445e-05,3.883291e-05,1.252545e-05,1.404126e-05,5.073429e-05,1.266151e-05,4.990268e-06,6.878563e-06,3.853327e-05,2.598077e-05,1.131652e-05,1.464521e-05,2.247049e+01,2.610737e+01
min,-9.152096e-04,-1.942183e-03,-1.034595e-04,-1.105371e-04,-6.541168e-04,-1.483897e-03,-3.825000e-04,-5.824306e-04,-1.069842e-03,-3.998122e-04,-4.717583e-05,-2.395028e-04,-1.448422e-03,-7.321497e-04,-4.896206e-04,-5.471918e-04,-2.303978e+01,-4.305778e+00
25%,-7.510078e-06,-9.420879e-06,-2.574322e-06,-2.526801e-06,-3.251968e-06,-5.218468e-06,-4.014682e-06,-3.202528e-06,-1.634931e-05,-5.657384e-06,-3.067547e-06,-3.441960e-06,-5.133208e-06,-5.534016e-06,-2.613644e-06,-3.334542e-06,1.055990e+01,2.152889e+01
50%,1.151889e-06,2.232721e-06,9.899731e-08,1.512165e-08,2.675181e-07,1.913958e-07,0.000000e+00,2.091450e-07,2.152981e-06,4.667680e-09,-4.117406e-08,-1.138556e-07,-3.423430e-07,6.472018e-07,1.134401e-07,2.199274e-07,1.535985e+01,2.927929e+01
75%,9.020946e-06,1.495654e-05,2.747421e-06,2.573463e-06,3.954990e-06,6.231710e-06,4.157251e-06,3.533766e-06,2.017061e-05,5.822982e-06,3.022782e-06,3.289759e-06,3.715752e-06,7.813156e-06,2.905086e-06,3.718127e-06,2.495976e+01,3.444622e+01
max,5.866060e-04,1.272647e-03,1.171567e-04,2.089401e-04,5.052245e-04,1.107698e-03,2.704328e-04,4.218504e-04,6.151334e-04,4.196055e-04,6.285966e-05,2.190010e-04,1.858117e-03,6.020703e-04,4.632727e-04,6.572311e-04,9.311910e+01,1.119502e+02

In [22]:
EMG_Target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5135095 entries, 0 to 529098
Data columns (total 18 columns):
 #   Column          Dtype
---  ------          -----
 0   EMG1            float32
 1   EMG2            float32
 2   EMG3            float32
 3   EMG4            float32
 4   EMG5            float32
 5   EMG6            float32
 6   EMG7            float32
 7   EMG8            float32
 8   EMG9            float32
 9   EMG10           float32
 10  EMG11           float32
 11  EMG12           float32
 12  EMG13           float32
 13  EMG14           float32
 14  EMG15           float32
 15  EMG16           float32
 16  indexExtension  float32
 17  indexFlexion    float32
dtypes: float32(18)
memory usage: 391.8 MB

In [23]:
EMG_Target.isna().sum()

EMG1              0
EMG2              0
EMG3              0
EMG4              0
EMG5              0
EMG6              0
EMG7              0
EMG8              0
EMG9              0
EMG10             0
EMG11             0
EMG12             0
EMG13             0
EMG14             0
EMG15             0
EMG16             0
indexExtension    0
indexFlexion      0
dtype: int64

## Visualizing the Data

## Preprocessing Phase

In [24]:
duplicates_all = EMG_Target[EMG_Target.duplicated()]
duplicates_all.shape

(3627, 18)

In [25]:
EMG_Target = EMG_Target.drop_duplicates()

In [26]:
means = EMG_Target.mean()
stds = EMG_Target.std()
threshold = 4
outliers = EMG_Target[(np.abs((EMG_Target - means) / stds) > threshold).any(axis=1)]
outliers.shape

(465866, 18)

In [27]:
EMG_Target = EMG_Target[(np.abs((EMG_Target - means) / stds) <= threshold).all(axis=1)]
EMG_Target.shape

(4665602, 18)

In [28]:
EMG_Target.head(5)

,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,EMG7,EMG8,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

In [29]:
EMG_Target.columns = ['EMG1','EMG2','EMG3','EMG4','EMG5','EMG6','EMG7',
                      'EMG8','EMG9','EMG10','EMG11','EMG12','EMG13',
                      'EMG14','EMG15','EMG16','indexExtension','indexFlexion']
EMG_Target.head()

,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,EMG7,EMG8,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## PCA feature extraction

In [30]:
X = EMG_Target.drop(['indexExtension', 'indexFlexion'], axis=1).values

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

from sklearn.decomposition import PCA
pca = PCA(n_components=4)
X = pca.fit_transform(X)

In [31]:
## add 4 new features into the original dataset

In [32]:
X_pca = pd.DataFrame(X)
X_pca = X_pca.reset_index(drop=True)
X_pca.columns = ['PCA1', 'PCA2', 'PCA3', 'PCA4']
EMG_Target = EMG_Target.reset_index(drop=True)
X_pca.head()

       PCA1      PCA2      PCA3      PCA4
0 -0.363582 -0.076172 -0.094667 -0.617478
1 -0.312221  0.088616  0.414626 -0.447645
2  0.272062  0.427899  0.523729  0.058757
3  0.333933  0.441305  0.423305  0.148611
4  0.024402 -0.022232  0.173693 -0.290081

In [33]:
EMG_Target_new = pd.concat([X_pca,EMG_Target], axis=1)
EMG_Target_new.head()

,PCA1,PCA2,PCA3,PCA4,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,-0.363582,-0.076172,-0.094667,-0.617478,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-0.312221,0.088616,0.414626,-0.447645,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,0.272062,0.427899,0.523729,0.058757,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,0.333933,0.441305,0.423305,0.148611,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,0.024402,-0.022232,0.173693,-0.290081,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## FastICA feature extraction

In [34]:
from sklearn.decomposition import FastICA
X = EMG_Target.drop(['indexExtension', 'indexFlexion'], axis=1).values
ica = FastICA(n_components=4)
X_ica = ica.fit_transform(X)
X_ica = pd.DataFrame(X_ica, columns=['ICA1', 'ICA2', 'ICA3', 'ICA4'])
X_ica.shape

(4665602, 4)

In [35]:
X_ica.head()

       ICA1      ICA2      ICA3      ICA4
0  0.277743  0.348236 -0.245775 -0.032108
1  0.263020  0.321421 -0.151307 -0.072256
2  0.260145  0.196992 -0.221100 -0.031587
3  0.180705  0.134789 -0.261647 -0.019762
4  0.088378  0.157215 -0.287591 -0.016378

In [36]:
## add 4 new features into the original dataset

In [37]:
EMG_Target_new = pd.concat([X_ica,EMG_Target_new], axis=1)
EMG_Target_new.head()

,ICA1,ICA2,ICA3,ICA4,PCA1,PCA2,PCA3,PCA4,EMG1,EMG2,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,0.277743,0.348236,-0.245775,-0.032108,-0.363582,-0.076172,-0.094667,-0.617478,-1.221389e-05,0.000013,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,0.263020,0.321421,-0.151307,-0.072256,-0.312221,0.088616,0.414626,-0.447645,-1.103459e-05,0.000012,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,0.260145,0.196992,-0.221100,-0.031587,0.272062,0.427899,0.523729,0.058757,-5.559594e-07,0.000010,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,0.180705,0.134789,-0.261647,-0.019762,0.333933,0.441305,0.423305,0.148611,4.855902e-06,0.000007,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,0.088378,0.157215,-0.287591,-0.016378,0.024402,-0.022232,0.173693,-0.290081,3.194906e-06,0.000004,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## t-SNE feature extraction

from sklearn.manifold import TSNE
X = EMG_Target.drop(['indexExtension', 'indexFlexion'], axis=1).values
tsne = TSNE(n_components=3)
X_tsne = tsne.fit_transform(X)
X_tsne.shape

## ISOMAP & LLE feature extraction

from sklearn.manifold import Isomap, LocallyLinearEmbedding
X = EMG_Target.drop(['indexExtension', 'indexFlexion'], axis=1).values
Isomap = Isomap(n_components=4)
Isomap_features = Isomap.fit_transform(X)
lle = LocallyLinearEmbedding(n_components=2)
lle_features = lle.fit_transform(X)

## Polynomial Features

In [38]:
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd

# Assume 'df' is your dataset with features
X = EMG_Target.drop(columns=['indexExtension', 'indexFlexion'])

# Generate polynomial features of degree 2 (including interaction terms)
poly = PolynomialFeatures(degree=1, include_bias=False)
X_poly = poly.fit_transform(X)
X_poly.shape

(4665602, 16)

In [39]:
X_poly = pd.DataFrame(X_poly, columns=['Poly1', 'Poly2', 'Poly3', 'Poly4',
                                      'Poly5', 'Poly6', 'Poly7', 'Poly8',
                                      'Poly9', 'Poly10', 'Poly11', 'Poly12',
                                      'Poly13', 'Poly14', 'Poly15', 'Poly16'])
X_poly.head()

,Poly1,Poly2,Poly3,Poly4,Poly5,Poly6,Poly7,Poly8,Poly9,Poly10,Poly11,Poly12,Poly13,Poly14,Poly15,Poly16
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003

In [40]:
EMG_Target_new = pd.concat([X_poly,EMG_Target_new], axis=1)
EMG_Target_new.head()

,Poly1,Poly2,Poly3,Poly4,Poly5,Poly6,Poly7,Poly8,Poly9,Poly10,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,-1.221389e-05,0.000013,1.417190e-06,-1.450381e-06,8.927418e-07,1.276400e-06,-0.000004,-2.097067e-06,-0.000011,-0.000002,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,-1.103459e-05,0.000012,-8.082592e-07,-2.964917e-06,1.620494e-06,1.319671e-07,-0.000002,-2.095100e-06,-0.000007,-0.000001,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,-5.559594e-07,0.000010,-9.035197e-07,-8.051478e-07,1.478138e-06,-3.573351e-06,-0.000002,-2.915417e-07,-0.000010,0.000005,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,4.855902e-06,0.000007,-9.693842e-07,1.651934e-07,2.062703e-06,-5.654433e-06,-0.000003,5.621391e-07,-0.000011,0.000007,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,3.194906e-06,0.000004,-1.149470e-06,7.105700e-07,6.009558e-06,-5.201861e-06,-0.000006,-2.785616e-07,-0.000011,0.000005,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## Binning/ Discretization

In [41]:
import pandas as pd

# Assume 'df' is your dataset with continuous features
X = EMG_Target.drop(columns=['indexExtension', 'indexFlexion'])

# Apply binning (discretization)
X_binned = X.apply(lambda col: pd.cut(col, bins=100, labels=False))

X_binned.head()

,EMG1,EMG2,EMG3,EMG4,EMG5,EMG6,EMG7,EMG8,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16
0,45,53,53,45,50,50,45,48,47,48,47,46,50,51,49,53
1,45,53,47,41,51,50,47,48,48,48,56,49,50,53,49,58
2,49,52,47,47,51,48,48,49,47,55,65,55,49,54,47,55
3,51,51,47,50,52,48,46,50,47,57,63,58,48,54,46,53
4,51,50,47,52,56,48,43,49,47,54,48,56,48,53,47,52

In [42]:
X_binned.columns = ['Bin1','Bin2','Bin3','Bin4','Bin5','Bin6','Bin7',
                      'Bin8','Bin9','Bin10','Bin11','Bin12','Bin13',
                      'Bin14','Bin15','Bin16']
X_binned.head()

,Bin1,Bin2,Bin3,Bin4,Bin5,Bin6,Bin7,Bin8,Bin9,Bin10,Bin11,Bin12,Bin13,Bin14,Bin15,Bin16
0,45,53,53,45,50,50,45,48,47,48,47,46,50,51,49,53
1,45,53,47,41,51,50,47,48,48,48,56,49,50,53,49,58
2,49,52,47,47,51,48,48,49,47,55,65,55,49,54,47,55
3,51,51,47,50,52,48,46,50,47,57,63,58,48,54,46,53
4,51,50,47,52,56,48,43,49,47,54,48,56,48,53,47,52

In [43]:
EMG_Target_new = pd.concat([X_binned,EMG_Target_new], axis=1)
EMG_Target_new.head()

,Bin1,Bin2,Bin3,Bin4,Bin5,Bin6,Bin7,Bin8,Bin9,Bin10,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,45,53,53,45,50,50,45,48,47,48,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,45,53,47,41,51,50,47,48,48,48,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,49,52,47,47,51,48,48,49,47,55,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,51,51,47,50,52,48,46,50,47,57,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,51,50,47,52,56,48,43,49,47,54,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## FFT ( Fourirer Transform Features )

In [44]:
import numpy as np
import pandas as pd

# Assume 'df' is your dataset with time-series EMG data
X = EMG_Target.drop(columns=['indexFlexion', 'indexExtension'])

# Compute Fourier Transform for each signal
X_ft = np.fft.fft(X, axis=0)

# Get the magnitudes of the Fourier coefficients
X_ft_magnitude = np.abs(X_ft)

# Create a new DataFrame with Fourier-based features
X_ft_df = pd.DataFrame(X_ft_magnitude)

X_ft_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,2.478156,4.195687,0.340390,0.257321,1.046192,1.482549,0.623560,0.485581,3.586884,0.498167,0.166927,0.153300,1.087656,2.406621,0.744107,0.949946
1,0.296876,0.374036,0.013479,0.007599,0.056011,0.285469,0.045906,0.168720,0.266067,0.087788,0.019927,0.072953,0.231107,0.431859,0.040128,0.162910
2,0.718733,0.295363,0.046834,0.043323,0.304123,0.563262,0.240994,0.207919,0.971118,0.196275,0.026757,0.035080,0.182174,0.091129,0.214825,0.326105
3,0.388575,0.401546,0.027967,0.017032,0.131661,0.318585,0.089124,0.070958,0.472088,0.098266,0.014170,0.093527,0.073932,0.282463,0.081293,0.142298
4,0.302529,0.771766,0.046064,0.004067,0.147307,0.121351,0.084972,0.026341,0.602825,0.110302,0.006037,0.073376,0.279727,0.401860,0.137390,0.156683

In [45]:
X_ft_df.columns = ['FT1','FT2','FT3','FT4','FT5','FT6','FT7',
                      'FT8','FT9','FT10','FT11','FT12','FT13',
                      'FT14','FT15','FT16']
X_ft_df.head()

,FT1,FT2,FT3,FT4,FT5,FT6,FT7,FT8,FT9,FT10,FT11,FT12,FT13,FT14,FT15,FT16
0,2.478156,4.195687,0.340390,0.257321,1.046192,1.482549,0.623560,0.485581,3.586884,0.498167,0.166927,0.153300,1.087656,2.406621,0.744107,0.949946
1,0.296876,0.374036,0.013479,0.007599,0.056011,0.285469,0.045906,0.168720,0.266067,0.087788,0.019927,0.072953,0.231107,0.431859,0.040128,0.162910
2,0.718733,0.295363,0.046834,0.043323,0.304123,0.563262,0.240994,0.207919,0.971118,0.196275,0.026757,0.035080,0.182174,0.091129,0.214825,0.326105
3,0.388575,0.401546,0.027967,0.017032,0.131661,0.318585,0.089124,0.070958,0.472088,0.098266,0.014170,0.093527,0.073932,0.282463,0.081293,0.142298
4,0.302529,0.771766,0.046064,0.004067,0.147307,0.121351,0.084972,0.026341,0.602825,0.110302,0.006037,0.073376,0.279727,0.401860,0.137390,0.156683

In [46]:
EMG_Target_new = pd.concat([X_ft_df,EMG_Target_new], axis=1)
EMG_Target_new.head()

,FT1,FT2,FT3,FT4,FT5,FT6,FT7,FT8,FT9,FT10,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,2.478156,4.195687,0.340390,0.257321,1.046192,1.482549,0.623560,0.485581,3.586884,0.498167,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,0.296876,0.374036,0.013479,0.007599,0.056011,0.285469,0.045906,0.168720,0.266067,0.087788,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,0.718733,0.295363,0.046834,0.043323,0.304123,0.563262,0.240994,0.207919,0.971118,0.196275,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,0.388575,0.401546,0.027967,0.017032,0.131661,0.318585,0.089124,0.070958,0.472088,0.098266,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,0.302529,0.771766,0.046064,0.004067,0.147307,0.121351,0.084972,0.026341,0.602825,0.110302,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## Statistical Features

In [47]:
import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis

# Assume 'df' is your dataset with time-series EMG data
X = EMG_Target.drop(columns=['indexFlexion','indexExtension'])

# Create statistical features (mean, variance, skewness, kurtosis)
def create_statistical_features(df):
    features = pd.DataFrame()
    features['mean'] = EMG_Target.mean(axis=1)
    features['variance'] = EMG_Target.var(axis=1)
    features['skewness'] = EMG_Target.apply(lambda x: skew(x), axis=1)
    features['kurtosis'] = EMG_Target.apply(lambda x: kurtosis(x), axis=1)
    return features

# Apply to the entire DataFrame
X_stat = create_statistical_features(X)

X_stat.head()

       mean   variance  skewness  kurtosis
0  2.719162  72.399574  3.056174  8.098740
1  2.719163  72.399567  3.056174  8.098740
2  2.719163  72.399559  3.056175  8.098742
3  2.719163  72.399567  3.056174  8.098740
4  2.719162  72.399567  3.056174  8.098740

In [48]:
EMG_Target_new = pd.concat([X_stat,EMG_Target_new], axis=1)
EMG_Target_new.head()

,mean,variance,skewness,kurtosis,FT1,FT2,FT3,FT4,FT5,FT6,...,EMG9,EMG10,EMG11,EMG12,EMG13,EMG14,EMG15,EMG16,indexExtension,indexFlexion
0,2.719162,72.399574,3.056174,8.098740,2.478156,4.195687,0.340390,0.257321,1.046192,1.482549,...,-0.000011,-0.000002,-1.004354e-06,-1.922719e-06,0.000002,0.000002,-3.563558e-07,0.000004,15.359853,33.585068
1,2.719163,72.399567,3.056174,8.098740,0.296876,0.374036,0.013479,0.007599,0.056011,0.285469,...,-0.000007,-0.000001,2.537384e-06,-4.171008e-07,0.000002,0.000008,-7.699463e-08,0.000010,15.359853,33.585068
2,2.719163,72.399559,3.056175,8.098742,0.718733,0.295363,0.046834,0.043323,0.304123,0.563262,...,-0.000010,0.000005,6.192121e-06,3.181949e-06,-0.000003,0.000010,-2.545980e-06,0.000006,15.359853,33.585068
3,2.719163,72.399567,3.056174,8.098740,0.388575,0.401546,0.027967,0.017032,0.131661,0.318585,...,-0.000011,0.000007,5.304991e-06,4.584006e-06,-0.000005,0.000010,-3.513715e-06,0.000004,15.359853,33.585068
4,2.719162,72.399567,3.056174,8.098740,0.302529,0.771766,0.046064,0.004067,0.147307,0.121351,...,-0.000011,0.000005,-7.471688e-07,3.766795e-06,-0.000003,0.000007,-2.335792e-06,0.000003,15.359853,33.585068

## Feature selection

In [49]:
from sklearn.feature_selection import SelectKBest, f_classif
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1)
y = EMG_Target_new[['indexExtension', 'indexFlexion']]
selector = SelectKBest(score_func=f_classif, k=30)
selected_features = selector.fit_transform(X, y['indexExtension'])
selected_indices = selector.get_support(indices=True)
selected_feature_names = [X.columns[i] for i in selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

Selected Features:
mean
variance
skewness
kurtosis
FT1
FT2
FT3
FT4
FT5
FT6
FT7
FT8
FT9
FT10
FT11
FT12
FT13
FT14
FT15
FT16
Bin1
Bin16
Poly1
Poly15
Poly16
ICA3
PCA1
EMG1
EMG15
EMG16

In [50]:
from sklearn.linear_model import Lasso
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1)
y = EMG_Target_new[['indexExtension', 'indexFlexion']]
lasso = Lasso(alpha=0.005)
lasso.fit(X, y['indexExtension'])
feature_importances = lasso.coef_
selected_indices = np.nonzero(feature_importances)[0]
selected_feature_names = X.columns[selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

Selected Features:
mean
variance
skewness
kurtosis
FT6
Bin1
Bin2
Bin3
Bin4
Bin5
Bin6
Bin7
Bin8
Bin9
Bin10
Bin11
Bin12
Bin13
Bin14
Bin15
Bin16

In [51]:
from sklearn.feature_selection import SelectKBest, f_classif
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1)
y = EMG_Target_new[['indexExtension', 'indexFlexion']]
selector = SelectKBest(score_func=f_classif, k=30)
selected_features = selector.fit_transform(X, y['indexFlexion'])
selected_indices = selector.get_support(indices=True)
selected_feature_names = [X.columns[i] for i in selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

Selected Features:
mean
variance
skewness
kurtosis
FT1
FT2
FT3
FT4
FT5
FT6
FT7
FT8
FT9
FT10
FT11
FT12
FT13
FT14
FT15
FT16
Bin1
Bin5
Bin16
Poly1
Poly5
Poly16
PCA1
EMG1
EMG5
EMG16

In [52]:
from sklearn.linear_model import Lasso
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1)
y = EMG_Target_new[['indexExtension', 'indexFlexion']]
lasso = Lasso(alpha=0.005)
lasso.fit(X, y['indexFlexion'])
feature_importances = lasso.coef_
selected_indices = np.nonzero(feature_importances)[0]
selected_feature_names = X.columns[selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

Selected Features:
mean
variance
skewness
kurtosis
FT6
Bin1
Bin2
Bin3
Bin4
Bin5
Bin6
Bin7
Bin8
Bin9
Bin10
Bin11
Bin12
Bin13
Bin14
Bin15
Bin16

In [53]:
EMG_Target_new.shape

(4665602, 78)

corr_matrix = EMG_Target.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

## Implenting ANN

In [54]:
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1).values
y = EMG_Target_new[['indexExtension']].values

In [55]:
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [57]:
X_train.shape

(3732481, 76)

In [ ]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

# Create the ANN model
model = Sequential()

model.add(Dense(256, activation='relu'))
model.add(Dropout(0.1))  

model.add(Dense(128, input_dim=76, activation='relu'))
model.add(Dropout(0.1))  

model.add(Dense(64, activation='relu'))  
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))  
model.add(Dropout(0.1)) 

model.add(Dense(1, activation='linear'))  


model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


history = model.fit(X_train, y_train, epochs=75, batch_size=16, validation_data=(X_test, y_test))


test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss (MSE): {test_loss}")
print(f"Test Mean Absolute Error (MAE): {test_mae}")

# Make predictions
predictions = model.predict(X_test)

C:\Users\Bashir Rayaneh\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 315s 1ms/step - loss: 28.2899 - mae: 3.0451 - val_loss: 14.0309 - val_mae: 2.3044
Epoch 2/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 302s 1ms/step - loss: 16.3204 - mae: 2.2910 - val_loss: 12.6835 - val_mae: 2.1905
Epoch 3/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 306s 1ms/step - loss: 15.0055 - mae: 2.2202 - val_loss: 10.1560 - val_mae: 1.7701
Epoch 4/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 308s 1ms/step - loss: 14.5479 - mae: 2.2058 - val_loss: 10.0730 - val_mae: 1.7463
Epoch 5/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 325s 1ms/step - loss: 14.3515 - mae: 2.1977 - val_loss: 12.0372 - val_mae: 2.2526
Epoch 6/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 325s 1ms/step - loss: 14.2486 - mae: 2.1983 - val_loss: 9.6878 - val_mae: 1.6940
Epoch 7/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 350s 1ms/step - loss: 14.2480 - mae: 2.2047 - val_loss: 9.2132 - val_mae: 1.5876
Epoch 8/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 361s 2ms/step - loss: 14.2865 - mae: 2.2133 - val_loss: 10.1861 - val_mae: 1.7083
Epoch 9/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 356s 2ms/step - loss: 14.3385 - mae: 2.2207 - val_loss: 8.8303 - val_mae: 1.4986
Epoch 10/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 344s 1ms/step - loss: 14.4103 - mae: 2.2253 - val_loss: 11.2670 - val_mae: 1.8697
Epoch 11/75
233281/233281 ━━━━━━━━━━━━━━━━━━━━ 372s 2ms/step - loss: 14.3120 - mae: 2.2190 - val_loss: 11.3794 - val_mae: 2.0592
Epoch 12/75
  8326/233281 ━━━━━━━━━━━━━━━━━━━━ 4:58 1ms/step - loss: 14.5373 - mae: 2.2429

In [ ]:
X = EMG_Target_new.drop(['indexExtension', 'indexFlexion'], axis=1).values
y = EMG_Target_new[['indexFlexion']].values

In [ ]:
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train.shape

In [ ]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

# Create the ANN model
model = Sequential()

model.add(Dense(256, input_dim=76, activation='relu'))
model.add(Dropout(0.1)) 

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.1))  

model.add(Dense(64, activation='relu'))  
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))  
model.add(Dropout(0.1)) 

model.add(Dense(1, activation='linear'))  


model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])


history = model.fit(X_train, y_train, epochs=75, batch_size=16, validation_data=(X_test, y_test))


test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test Loss (MSE): {test_loss}")
print(f"Test Mean Absolute Error (MAE): {test_mae}")

# Make predictions
predictions = model.predict(X_test)